ip2location:
  v1:
    baseUrl: http://localhost:8080/stubs/ip
#    baseUrl: https://api.ip2location.io
    apiKey: 1234
newsapi:
  v2:
    baseUrl: http://localhost:8080/stubs/news
#    baseUrl: https://newsapi.org/v2
    apiKey: 1234
openweathermap:
  v3:
    baseUrl: http://localhost:8080/stubs/weather
#    baseUrl: https://api.openweathermap.org/data/3.0
    apiKey: 1234
batch:
  news:
    # Every 5 minutes - https://crontab.cronhub.io/
    fixedScheduleCron: '0 */5 * * * * '